url: http://communicaretreinamentos.com.br
baseurl:

# Site settings
title: Communicare Treinamentos
site_link: www.communicaretreinamentos.com.br
email: contato@communicaretreinamentos.com.br
description: "Centro de Treinamentos Communicare em Apucarana."


# Team names, titles and social links
people:
- name: Vinicius Campos
  gravatar: https://www.gravatar.com/avatar/f5acb91dd8c79d55830816eea7d12b60
  position: CEO | Coach
  page: vinicius-campos
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
    - title: linkedin
      url: http://www.linkedin.com/in/vinicampos
#    - title: google-plus
#      url: #
  description: |
    Vinicius Campos é CEO da Communicare Treinamentos graduado em sistemas de informação, pós graduado em banco de dados e psicopedagogia clínica e institucional é também professor universitário.
    Apaixonado por comunicação, neurociência e  comportamento humano também possui formação em programação neurolinguística.
    Especializou-se na arte de falar bem em público tornando-se orador e palestrante profissional.

#- name: Alessandro de Lima Folk
#  gravatar: https://www.gravatar.com/avatar/399d48b39ef431d4552a7be1e6947ae7
#  position: CTO | Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #


# Depoimentos
depoiments:
- name: Rita Sene
  img: rita_sene.jpeg
  description: Esse curso foi um grande aprendizado; procurei aproveitar todas as oportunidades oferecidas. Para minha vida pessoal e profissional foi um passo de crescimento. A convivência com os colegas acrescentou um novo vigor na caminhada da minha vida. Aprendi que a comunicação não é só ler ou falar um texto, é muito mais. Vou sentir falta, pois foi uma grande oportunidade que tive e fico mais feliz porque consegui vencer mais uma etapa da minha vida.
- name: Bianca Sofia
  img: bianca_sofia.jpeg
  description: O curso foi bem interessante, pois através dele aprendi técnicas de como me expressar melhor em uma apresentação, trabalhos ou palestras.
- name: Giselle Angela
  img: giselle_angela.jpeg
  description: O curso de oratória é muito eficaz e interessante para pessoas com dificuldade de falar em público. Aconselho a todas as pessoas fazerem, porque pra mim foi ótimo.
- name: Eduardo Cavasaki
  img: eduardo_cavasaki.jpeg
  description: O curso nos ajudou a desenvolver técnicas para melhor comunicação seja com uma ou várias pessoas. Algumas dessas técnicas são:&nbsp;Posicionamento, andar, gestos, falar com objetivo, controlar os sentimentos e criar alto confiança. Enfim, o curso é excelente e de grande valor para a nossa vida social e profissional.
- name: Stéfani Lopes
  img: stefani_lopes.jpeg
  description: O curso de oratória foi muito importante para eu perder o medo de falar em público. Agora é só praticar e confiar em mim. Quero agradecer muito ao professor Vinicius pelo curso e por essa oportunidade.
- name: Alisson Henrique
  img: alisson_henrique.jpeg
  description: Gostei muito do curso, acho de extrema importância a prática e seus métodos. Como o Vinicius diz:&nbsp;A evolução só vem com a experiência.
- name: Ana Carolina
  img: ana_carolina.jpeg
  description: Acredito que esse curso vai me ajudar e está ajudando em muitas situações do dia a dia. Comecei a ver as coisas por outro ângulo, sem contar que ajudou demais na questão do nervosismo, como se comportar em certos locais, entender quem eu sou e como funciono. Achei super interessante o curso, super indico, vai me ajudar bastante na vida profissional, nos trabalhos... vai me ajudar na vida em si. Me senti realizada.
- name: André Luis
  img: andre_luis.jpeg
  description: Ao se referir a evolução posso apontar esse curso como causa. Os sentimentos são trabalhados para que possamos enfrentar nossos medos diante do público. Em resumo o que posso dizer desta experiência é que as ténicas em conjunto com a prática trouxe resultados brilhantes.
- name: José Kazuo
  img: jose_kazuo.jpeg
  description: O curso possibilitou abrir a minha mente sobre muitos assuntos, e de como pequenos gestos causam um grande impacto. Ele também proporciona um controle sobre nossas emoções, técnicas  de como se portar diante do público em palestras e trabalhos. Foi muito trabalhado também a nossa linguagem corporal. Um curso totalmente prático.
- name: Welliton Gabriel
  img: welliton_gabriel.jpeg
  description: Me surpreendi com as dinâmicas deste curso, ele oferece técnicas que realmente me ajudou a enfrentar momentos com naturalidade que normalmente eu não resolveria de tal forma. É uma experiência nova, de grande utilidade pessoal e profissional. O treinamento alinha conhecimentos práticos e teóricos que são muito importantes.
- name: Bruno Felipe
  img: bruno_felipe.jpeg
  description: Sempre tive muita dificuldade em fazer apresentações, e foi essa dificuldade que me motivou a fazer o curso. Durante as aulas fui capaz de aprender técnicas que me ajudaram a superar o receio de apresentar alguns trabalhos, me portar com mais naturalidade perante. Atualmente continuo aplicando as técnicas aprendidas procurando melhorar cada dia.
- name: José Matheus
  img: jose_matheus.jpeg
  description: O curso de oratória foi para mim uma experiência de aprendizado para como se portar em uma apresentação, porém foi muito além disso, ele apresenta situações para se alto conhecer, descobrir e refletir sobre o que pode estar impedido de realizar as apresentações. Além de apresentar um conjunto de dicas e técnicas para como se portar, falar e finalizar apresentações. Resumindo é uma experiência que propõem muito conhecimento que ajudará nas futuras apresentações
- name: Maria Eduarda
  img: maria_eduarda.jpeg
  description: Desde pequena tive uma grande dificuldade em me comunicar com as pessoas, até mesmo as mais próximas. Quando o Professor Vinícius apresentou o curso de oratória, percebi que seria uma ótima oportunidade para melhorar, inclusive para minha vida acadêmica e profissional. Depois do curso senti grande diferença em  minha comunicação, consigo me expressar com mais facilidade.  Aprendi como me portar apresentando um TCC, uma palestra, me dando mais segurança para realizar um bom desempenho! E principalmente, despertou meu interesse para aprimorar mais a minha didática.
- name: Henrique Cabral
  img: henrique_cabral.jpeg
  description: Ao participar deste curso de oratória tive contato com novas pessoas que me ajudaram à enfrentar a dificuldade que tenho para me expressar perante outras. Este curso somou muito para meu conhecimento me ajudando à apresentar melhor trabalhos em sala de aula. Aprendi a lidar com ansiedade e o medo de falar em público, me portar perante ao público. Recomendo este curso a todos,irá somar muito a sua vida acadêmica,pessoal e profissional.



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CommunicareBR
  - title: facebook
    url: https://www.facebook.com/CommunicareTreinamentos
  - title: instagram
    url: https://www.instagram.com/CommunicareTreinamentos

# Postal address (add as many lines as necessary)
address:
  - line: Apucarana - PR
  - line: Brasil

# Build settings
markdown: kramdown
permalink: pretty