url: http://communicaretreinamentos.com.br
baseurl:

# Site settings
title: Communicare Treinamentos
site_link: www.communicaretreinamentos.com.br
email: contato@communicaretreinamentos.com.br
description: "Centro de Treinamentos Communicare em Apucarana."


# Team names, titles and social links
people:
- name: Vinicius Campos
  gravatar: https://www.gravatar.com/avatar/f5acb91dd8c79d55830816eea7d12b60
  position: CEO | Coach
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
    - title: linkedin
      url: http://www.linkedin.com/in/vinicampos
#    - title: google-plus
#      url: #
  description: |
    Vinicius Campos é CEO da Communicare Treinamentos graduado em sistemas de informação, pós graduado em banco de dados e psicopedagogia clínica e institucional é também professor universitário.
    Apaixonado por comunicação, neurociência e  comportamento humano também possui formação em programação neurolinguística.
    Especializou-se na arte de falar bem em público tornando-se orador e palestrante profissional.

#- name: Alessandro de Lima Folk
#  gravatar: https://www.gravatar.com/avatar/399d48b39ef431d4552a7be1e6947ae7
#  position: CTO | Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CommunicareBR
  - title: facebook
    url: https://www.facebook.com/CommunicareTreinamentos
  - title: instagram
    url: https://www.instagram.com/CommunicareTreinamentos

# Postal address (add as many lines as necessary)
address:
  - line: Apucarana - PR
  - line: Brasil

# Build settings
markdown: kramdown
permalink: pretty